### ISSUE TITLE
Missing Dataset in NYC Simulation

### ISSUE THREAD

**Issue by WolfgangGross** [Samuel-Maddock/Apple-Differential-Privacy#1]
What dataset was used in the NYC Simulation. I couldn't find any information on 'data/train.csv'

**Comment by Samuel-Maddock** [comment]
I didn't upload the data due to size, but the NYC dataset refers to the NYC Taxi and Limousine Commission (TLC) dataset. I believe I use the train set from https://www.kaggle.com/c/nyc-taxi-trip-duration/data

A word of warning: I'm planning on deprecating this repo, I have slightly faster implementations of Apple's algorithms and when time permits I will be adding them to the pure-LDP repo (https://github.com/Samuel-Maddock/pure-LDP). I'm planning on making pure-LDP a proper Python LDP package, whereas the code here was written for simulations and is very undocumented.

A lot of the simulation stuff here I am also planning to move over and improve with documentation. Hopefully all this will happen within the next 2-3 weeks.

**Comment by WolfgangGross** [comment]
Thanks for the quick response. I was looking at Kaggle but was nut sure. Could also make it for with an other Long/ Lat dataset from Kaggle. Thanks for the hint I will have a look a pure-LDP.

**Comment by Samuel-Maddock** [comment]
Feel free to reach out if you have any other questions
